### ISSUE TITLE
"Cannot read property 'indexOf' of undefined"

### ISSUE THREAD

**Issue by mickaelistria** [gorkem/vscode-k8s#22]
From Eclipse IDE, connecting to Language Server, I see

```
!ENTRY org.eclipse.lsp4e 1 0 2017-06-26 20:02:27.208
!MESSAGE RequestMessage
{
  "jsonrpc": "2.0",
  "id": "2",
  "method": "textDocument/completion",
  "params": {
    "textDocument": {
      "uri": "file:///home/mistria/sandbox/fefe/test.yaml"
    },
    "uri": "file:///home/mistria/sandbox/fefe/test.yaml",
    "position": {
      "line": 0,
      "character": 0
    }
  }
}

!ENTRY org.eclipse.lsp4e 4 0 2017-06-26 20:02:27.211
!MESSAGE Request textDocument/completion failed with message: Cannot read property 'indexOf' of undefined
!STACK 0
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/completion failed with message: Cannot read property 'indexOf' of undefined
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.logMessage(ProjectSpecificLanguageServerWrapper.java:283)
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.lambda$1(ProjectSpecificLanguageServerWrapper.java:226)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
```

Any hint?

**Comment by JPinkney** [comment]
It looks like it has something to do with the autocompletion section indexOf was called twice to filter out duplicate nodes. Can you paste the contents of the file by any chance?

**Comment by mickaelistria** [comment]
Sure I can: `` it's an empty file.

**Comment by JPinkney** [comment]
Interesting. When I try it in VS code no errors show up. Also the findNode thats called in yamlCompletion returns undefined (which it should) which then leads into autoCompletor.searchAll() which has no indexOf. I'll look into it more.

**Comment by mickaelistria** [comment]
Do you think it could be related to the nodejs version or something like
this? Is there a way to trigger more verbose error message on the server?

**Comment by JPinkney** [comment]
I'm currently running this on node v6.10.3 at work (just for reference) and I'm not sure yet if there's any way to set more verbose messages but I'll look into it.

**Comment by mickaelistria** [comment]
Might be `filesToIgnore` that's null. Is there some additional message to send to server after the `initialize` one to make it work?

**Comment by JPinkney** [comment]
You are right. I'm pretty sure I've narrowed down the issue. The k8s.filesNotValidating that the filesToIgnore pulls from is set in the client package.json not the server. I'm guessing because you are testing it with eclipse you don't need the client? (let me know about this) and thus the k8s.filesNotValidating is not being set. I'll make note of this in my own branch!

**Comment by mickaelistria** [comment]
Right, from Eclipse IDE, I start the Language Server from command-line as a separate process (`node vscode-k8s/client/server/src/server.js --stdio`). I have no other way to interact with it than with the LSP operations over the streams.

**Comment by JPinkney** [comment]
At least I know whats causing the issue now and can fix that!

**Comment by JPinkney** [comment]
I was able to reproduce this in eclipse. The issue has been fixed in the newest release and has not happen for me in eclipse again. Let me know if its fixed from your end!

**Comment by mickaelistria** [comment]
Thanks a lot Josh! I tried the new version on master and I could see all the nice features of this LS enabled and run everything just like it happens on the Gif video on VSCode.
So I'm definitely happy with it.
Note for self: commit https://github.com/gorkem/vscode-k8s/commit/4b0ed762c0ed7821823a972099ad165048d5df01 is good for demo in Eclipse IDE.
