### ISSUE TITLE
Error with language server

### ISSUE THREAD

**Issue by mickaelistria** [gorkem/vscode-k8s#5]
Just after a `cd server; npm install; npm run compile; cd ../client/server`, I try to connect to the language server from Eclipse IDE. On opening an empty `dummy.k8s` file, I see:

```
/home/mistria/workspace/com.redhat.kubernetes.lsp.eclipse/language-servers/server.js:109
    if (yDoc.errors) {
            ^

TypeError: Cannot read property 'errors' of undefined
    at validateTextDocument (/home/mistria/workspace/com.redhat.kubernetes.lsp.eclipse/language-servers/server.js:109:13)
    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (/home/mistria/workspace/com.redhat.kubernetes.lsp.eclipse/language-servers/server.js:96:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by mickaelistria** [comment]
Seems like that some of the necessary node_modules are not copied during `npm run compile`.

**Comment by mickaelistria** [comment]
Ignore my previous comment, it's not useful. What's strange is that I can actually see YAMLDocument interface in index.ts, but not in the index.js from the same node_module...

**Comment by JPinkney** [comment]
I found that issue earlier and fixed it my fork already! This repo isn't currently being worked on so anything in this repo was here before I started working on it ~2 weeks ago. I'm currently working on my fork https://github.com/JPinkney/vscode-k8s and will do a pull request when both validation and auto completion are finished (should be soon). Both are working but there's a couple bugs in the open source parser that we are using that I have to fix first

**Comment by mickaelistria** [comment]
Thanks for the info @JPinkney , much appreciated! I will probably give a try to your fork soon. Should I open PRs against your fork (for example for #3) ?

**Comment by JPinkney** [comment]
You can if you'd like and then everything from my fork will be pushed into this repository eventually. I'll go ahead and merge #3 though and then bring it into my repo!

**Comment by mickaelistria** [comment]
@JPinkney is this fix on the master branch of this repo? If so, can we close this issue?

**Comment by JPinkney** [comment]
Yes, this would have been fixed when I merged a bunch of my patches a couple of days ago, I'll close it

**Comment by JPinkney** [comment]
Is the issue at the same line again? Or is it at line 176? I did another call to the yamlLoader at 176 and didn't check for undefined there.

**Comment by mickaelistria** [comment]
line 109 again

**Comment by JPinkney** [comment]
Hmm line 109 in the current version is "interface filesToIgnore {" so i'm not sure how that can have any effect on it. Line 156 is the start of the validation function where it was happening before. I'll look into it more

**Comment by mickaelistria** [comment]
Your previous answer put me on the right track: it was my local strategy to fetch the LS which was relying on an out-of-date cache. I could upgrade and will open separate issues if necessary, now I'm using the right code.
Sorry about the noise.
