### ISSUE TITLE
completion/validation on kind

### ISSUE THREAD

**Issue by jstrachan** [gorkem/vscode-k8s#7]
I thought completion wasn't working on metadata's name/labels/annotations etc
![foo_yml_-_fabric8-team-components](https://user-images.githubusercontent.com/30140/27001555-b2326146-4dc4-11e7-8bf7-5971e6afb17d.png)
 turns out I'd made a typo in the `kind` but the LSP didn't warn me or offer completion

**Comment by jstrachan** [comment]
DOH - spot the obvious mistake on the kind :) I guess completion on kind would be good too

**Comment by JPinkney** [comment]
Hi! I've looked into this and this actually has more to do with the default VS code settings then it does the extension. For some reason by default in the user settings under editor, editor.quickSuggestions is false for strings and thats whats needed in order for autocompletion to work. When editor.quickSuggestions string is set to true this is what you should see:

![kind autocomplete](http://i.imgur.com/hzRPfs4.png)

![labels autocomplete](http://i.imgur.com/SMqmTDJ.png)

![gen autocomplete](http://i.imgur.com/gnMFY8X.png)

![name autocomplete](http://i.imgur.com/zN6bgZl.png)

I will update the readme so anyone else who tests this knows!!

**Comment by jstrachan** [comment]
Also there's no completion for the values of `kind` which should autocomplete all the known kinds like `Deployment`, `Secret` etc etc

**Comment by JPinkney** [comment]
I've added this this in the newest release!
